### PR TITLE
Refactor Concourse folder structure

### PR DESCRIPTION
**Pull request by malston**
This folder structure is makes it a little easier to tell which shell scripts are tasks and which are shared. I find it a little easier to navigate in an editor as well. Thoughts?

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@nebhale @philwebb @mbhave - you are Concourse experts - what do you think about this change? Does the pipeline look more Concourse like? As a reminder: one of the issues with Spring Cloud Pipelines and Concourse was the fact that I initially wrote it in the way I work with Jenkins. The idea of this PR is to refactor the current Concourse structure to better reflect the way developers work with it.

**Comment by mbhave** [comment]
@marcingrzejszczak I prefer having a `scripts` folder and a `tasks` folder to separate the `yml` and shell scripts. Somewhat similar to what concourse itself does for its CI [here](https://github.com/concourse/concourse/tree/master/ci) but with the `.yml` files put in a tasks folder instead.

**Comment by philwebb** [comment]
Same here. [Here's how `artifactory-resource` is structured](https://github.com/philwebb/artifactory-resource/tree/master/ci)

**Comment by marcingrzejszczak** [comment]
@malston says that some of the Labs teams are working like the way he presented. I guess it's not a gigantic difference between the 2 approaches, isn't it?

**Pull request merged**
