### PR TITLE
Provide a way to copy and source in custom scripts

### PR DESCRIPTION
**Pull request by malston**
Provides a way to hook in custom shell scripts that can override
the base functionality of a task. Spring Cloud Pipelines will source
custom scripts after all of its scripts have been sourced. By default,
it will look for custom scripts relative to the `ciscripts` directory
under `custom/` or if you set the `CUSTOM_SCRIPT_IDENTIFIER` var, then
it will look for them there instead. For example, to customize the
build-and-upload task all you would need to do is provide a script
called `build_and_upload.sh` in your `common/src/main/bash/custom/`
folder and Spring Cloud Pipelines will automatically source it in.
Then, you can override the build function in
`common/src/main/bash/projectType/pipeline-${projectType}` with your
own without re-writing all the logic up to that point.

Here’s an example that uses [it](https://github.com/malston/github-webhook/blob/spike-150749835/ci/pipeline.yml#L296).
Notice that I set an env var that tells sc-pipelines where to find my
custom script(s).

Then you’ll notice that I put my custom scripts in
`common/src/main/bash/${CUSTOM_SCRIPT_IDENTIFIER}` like [so](https://github.com/pivotalservices/pcf-apptx-pipelines/tree/spike-150749835/common/src/main/bash/apptx)

All my custom script does is source in a
`projectType/pipeline-${PROJECT_TYPE}` located inside the task folder
for that particular task. That way when the build function gets called
by sc-pipelines from the `${SCRIPTS_OUTPUT_FOLDER}/build_and_upload.sh`,
it will call a custom build function instead of the sc-pipeline one.

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
I think that it would be good to add some info in the docs about this. We can copy paste the sample usage. WDYT?

**Comment by marcingrzejszczak** [comment]
@malston , try rebasing against master cause there were quite a few changes with the docs

**Comment by malston** [comment]
Ugh, I accidentally rebased twice. Do you want me to submit a new PR?

**Comment by marcingrzejszczak** [comment]
Nope - it's ok :)

**Pull request merged**
